### ISSUE TITLE
Как работать с целями?

### ISSUE THREAD

**Issue by nikitabuida** [naumstory/nuxtjs-yandex-metrika#2]
Дмитрий, подскажите как правильно вызвать код метрики для передачи достижения цели?
Я правильно понял, что плагин создает объект window.counterXXXX на котором можно вызвать метод reachGoal('goalname')?

**Comment by aSpectro** [comment]
> Дмитрий, подскажите как правильно вызвать код метрики для передачи достижения цели?
> Я правильно понял, что плагин создает объект window.counterXXXX на котором можно вызвать метод reachGoal('goalname')?

Вы нашли решение, как вызвать reachGoal?

**Comment by naumstory** [comment]
Именно так
